# Enviar un correo si falla el codigo
name: EnviarCorreoFalla

# Controlar cuando correr el codigo, workflow para correrlo con boton
on:
  workflow_dispatch: 

permissions: 
  contents: write

jobs:
  extraer:
    name: Extraer ZIP del INEGI
    # Tipo de computadora a utilizar
    runs-on: windows-latest

    # Pasos a realizar
    steps:
      # Descargar el repositorio
      - name: Repositorio
        uses: actions/checkout@v4
      
      # Instalar Python
      - name: Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      # Instalar paquetes
      - name: Install packages
        run: |
          python -m pip install --upgrade pip 
          pip install datetime requests zipfile36 pandas openpyxl traceback2
      
      # Correr codigo
      - name: Ejecutar python
        run: python Extraer.py

      # Guardar cambios
      - name: Commit files
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "actions@github.com"
          git add .
          git diff --cached --quiet || git commit -m "Actualización automática"
          git push
